name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Ajustado para uma versão comum

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# A seção 'flutter:' é a principal.
flutter:
  uses-material-design: true

  # --- CORREÇÃO IMPORTANTE AQUI ---
  # A palavra 'assets:' deve ter 2 espaços antes,
  # para ficar "dentro" da seção 'flutter:'.
  assets:
    # O traço e o caminho devem ter 4 espaços antes.
    - assets/images/

